name: build and push image

on:
  repository_dispatch: 
  push:
    branches:
      - 'main'
  pull_request: 
    branches: 
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: elyes000/arkade
      - name: Create KIND Cluster
        uses: helm/kind-action@v1.2.0

    # Deploy to KIND Cluster
      - name: Deploy to KIND
        run: |
          kubectl apply -f deployment.yaml
